name: valentino
description: "A new Flutter package project."
version: 1.0.1
homepage: https://github.com/BerkeAytas/valentino
repository: https://github.com/BerkeAytas/valentino

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
